posgres:

craetedb:
	createdb --username=root --owner=root my_bank
	
migrateup:
	migrate -path db/migration -database "postgresql://root:secret@localhost:5432/my_bank?sslmode=disable" -verbose up

migratedown:
	migrate -path db/migration -database "postgresql://root:secret@localhost:5432/my_bank?sslmode=disable" -verbose down
sqlc:
	docker run --rm -v ${PWD}:/src -w /src kjconroy/sqlc generate

.PHONY:craetedb migrateup migratedown sqlc
